# Generated by Django 4.0.5 on 2022-07-02 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Entrepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomExp', models.CharField(max_length=50)),
                ('nomProd', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('adresse', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomProd', models.CharField(max_length=50)),
                ('nomLot', models.CharField(max_length=50)),
                ('dateRecep', models.DateField()),
                ('qte', models.PositiveIntegerField()),
                ('poids', models.FloatField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrepot.categorie')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrepot.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('fournisseur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entrepot.fournisseur')),
            ],
            bases=('entrepot.fournisseur',),
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrepot.entrepot')),
                ('expedition', models.ManyToManyField(to='entrepot.expedition')),
                ('reception', models.ManyToManyField(to='entrepot.reception')),
            ],
        ),
        migrations.CreateModel(
            name='Palette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrepot.zone')),
            ],
        ),
        migrations.AddField(
            model_name='expedition',
            name='reception',
            field=models.ManyToManyField(to='entrepot.reception'),
        ),
        migrations.AddField(
            model_name='expedition',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrepot.client'),
        ),
    ]
