# Generated by Django 4.0.5 on 2022-07-19 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('dateCreation', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conteneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numCon', models.CharField(max_length=100)),
                ('dateCreation', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entrepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=50)),
                ('dateCreation', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomExp', models.CharField(max_length=50)),
                ('dateExp', models.DateField()),
                ('dateCreation', models.DateField(auto_now_add=True)),
                ('conteneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrepot.conteneur')),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('adresse', models.CharField(max_length=200)),
                ('dateCreation', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomRecep', models.CharField(max_length=30)),
                ('dateRecep', models.DateField()),
                ('dateCreation', models.DateField(auto_now_add=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrepot.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('qteMax', models.IntegerField()),
                ('qteActu', models.IntegerField()),
                ('dateCreation', models.DateField(auto_now_add=True)),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrepot.entrepot')),
                ('expedition', models.ManyToManyField(to='entrepot.expedition')),
                ('reception', models.ManyToManyField(to='entrepot.reception')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomProd', models.CharField(max_length=50)),
                ('dateCreation', models.DateField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrepot.categorie')),
                ('reception', models.ManyToManyField(to='entrepot.reception')),
            ],
            options={
                'verbose_name': 'Produit',
            },
        ),
        migrations.CreateModel(
            name='LigneReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numLot', models.CharField(max_length=100)),
                ('dateCreation', models.DateField(auto_now_add=True)),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrepot.expedition')),
                ('reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrepot.reception')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrepot.zone')),
            ],
        ),
    ]
