# Generated by Django 4.0.5 on 2022-07-21 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrepot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignereception',
            name='expedition',
        ),
    ]
