# Generated by Django 4.0.5 on 2022-07-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zone',
            options={'verbose_name': 'Zone'},
        ),
        migrations.AlterField(
            model_name='zone',
            name='qteActu',
            field=models.IntegerField(blank=True),
        ),
    ]
