# Generated by Django 4.0.5 on 2022-07-15 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrepot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produit',
            options={'verbose_name': 'Produit'},
        ),
    ]
