# Generated by Django 4.0.5 on 2022-07-03 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrepot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='fournisseur_ptr',
        ),
        migrations.RemoveField(
            model_name='expedition',
            name='client',
        ),
        migrations.RemoveField(
            model_name='expedition',
            name='reception',
        ),
        migrations.RemoveField(
            model_name='palette',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='fournisseur',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='entrepot',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='expedition',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='reception',
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Entrepot',
        ),
        migrations.DeleteModel(
            name='Expedition',
        ),
        migrations.DeleteModel(
            name='Fournisseur',
        ),
        migrations.DeleteModel(
            name='Palette',
        ),
        migrations.DeleteModel(
            name='Reception',
        ),
        migrations.DeleteModel(
            name='Zone',
        ),
    ]
