# Generated by Django 4.0.5 on 2022-07-24 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrepot', '0002_remove_lignereception_expedition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='expedition',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='reception',
        ),
        migrations.AddField(
            model_name='expedition',
            name='ligneReception',
            field=models.ForeignKey(default=60, on_delete=django.db.models.deletion.CASCADE, to='entrepot.lignereception'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expedition',
            name='qte',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lignereception',
            name='expedier',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
