# Generated by Django 4.0.5 on 2022-07-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepot', '0003_alter_zone_qteactu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='qteActu',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
