# Generated by Django 4.0.5 on 2022-07-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepot', '0003_remove_zone_expedition_remove_zone_reception_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conteneur',
            options={'verbose_name': 'Conteneur'},
        ),
        migrations.AlterField(
            model_name='lignereception',
            name='expedier',
            field=models.BooleanField(default=False),
        ),
    ]
