# Generated by Django 4.0.4 on 2022-07-09 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrepot', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conteneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numCon', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LigneReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numLot', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomProd', models.CharField(max_length=50)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrepot.categorie')),
            ],
        ),
        migrations.RemoveField(
            model_name='palette',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='expedition',
            name='client',
        ),
        migrations.RemoveField(
            model_name='expedition',
            name='nomProd',
        ),
        migrations.RemoveField(
            model_name='expedition',
            name='reception',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='nomLot',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='nomProd',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='poids',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='qte',
        ),
        migrations.AddField(
            model_name='expedition',
            name='dateExp',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='reception',
            name='nomRecep',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='adresse',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Palette',
        ),
        migrations.AddField(
            model_name='produit',
            name='reception',
            field=models.ManyToManyField(to='entrepot.reception'),
        ),
        migrations.AddField(
            model_name='lignereception',
            name='expedition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrepot.expedition'),
        ),
        migrations.AddField(
            model_name='lignereception',
            name='reception',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrepot.reception'),
        ),
        migrations.AddField(
            model_name='expedition',
            name='conteneur',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='entrepot.conteneur'),
        ),
    ]
