# Generated by Django 4.0.4 on 2022-07-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepot', '0004_conteneur_lignereception_produit_remove_palette_zone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reception',
            name='nomRecep',
            field=models.CharField(max_length=30),
        ),
    ]
