# Generated by Django 4.0.5 on 2022-07-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepot', '0004_alter_conteneur_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expedition',
            name='ligneReception',
        ),
        migrations.AddField(
            model_name='expedition',
            name='ligneReception',
            field=models.ManyToManyField(to='entrepot.lignereception'),
        ),
    ]
