# Generated by Django 4.0.5 on 2022-07-24 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrepot', '0005_remove_expedition_lignereception_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expedition',
            name='ligneReception',
        ),
        migrations.AddField(
            model_name='expedition',
            name='ligneReception',
            field=models.ForeignKey(default=63, on_delete=django.db.models.deletion.CASCADE, to='entrepot.lignereception'),
            preserve_default=False,
        ),
    ]
