# Generated by Django 4.0.5 on 2022-07-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepot', '0007_remove_expedition_lignereception_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedition',
            name='nomExp',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
