# Generated by Django 4.0.5 on 2022-07-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepot', '0008_alter_expedition_nomexp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedition',
            name='qte',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
