# Generated by Django 4.0.5 on 2022-07-25 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrepot', '0010_remove_expedition_lignereception_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneConteneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrepot.expedition')),
                ('ligneReception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrepot.lignereception')),
            ],
        ),
    ]
