# Generated by Django 4.0.5 on 2022-07-25 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrepot', '0011_ligneconteneur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligneconteneur',
            name='ligneReception',
        ),
        migrations.AddField(
            model_name='ligneconteneur',
            name='conteneur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='entrepot.conteneur'),
            preserve_default=False,
        ),
    ]
