# Generated by Django 4.0.5 on 2022-07-25 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrepot', '0012_remove_ligneconteneur_lignereception_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligneconteneur',
            name='expedition',
        ),
        migrations.AddField(
            model_name='ligneconteneur',
            name='ligneReception',
            field=models.ForeignKey(default=66, on_delete=django.db.models.deletion.CASCADE, to='entrepot.lignereception'),
            preserve_default=False,
        ),
    ]
