# Generated by Django 4.0.5 on 2022-07-25 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrepot', '0013_remove_ligneconteneur_expedition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignereception',
            name='expedition',
        ),
    ]
